---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.app }}
    version: {{ .Values.appVersion}}
    chart: {{ .Values.chart }}
    releaseName: {{ .Values.relaeseName}}
    commitId: {{ .Values.commitId}}
    gitBranch: {{ .Values.gitBranch }}
    gitRepoName: {{ .Values.gitRepo}}
    gitOrgName: {{ .Values.gitOrgName}}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        version: {{ .Values.appVersion}}
        chart: {{ .Values.chart }}
        releaseName: {{ .Values.relaeseName}}
        commitId: {{ .Values.commitId}}
        gitBranch: {{ .Values.gitBranch }}
        gitRepoName: {{ .Values.gitRepo}}
        gitOrgName: {{ .Values.gitOrgName}}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.artifactoryUrl }}/{{ .Values.dockerRepository }}/{{ .Values.serviceName }}:{{ .Values.imageTag }}"
        ports:
        - containerPort: {{ .Values.port | default 8080}}