# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: {{ .Values.name }}
#   labels:
#     app: {{ .Values.app }}
# spec:
#   replicas: {{ .Values.replicas }}
#   selector:
#     matchLabels:
#       app: {{ .Values.app }}
#   template:
#     metadata:
#       labels:
#         app: {{ .Values.app }}
#     spec:
#       containers:
#       - name: {{ .Values.name }}
#         image: "{{ .Values.artifactoryUrl }}/{{ .Values.dockerRepository }}/{{ .Values.serviceName }}:{{ .Values.serviceTag }}"
#         ports:
#         - containerPort: {{ .Values.port }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: "found.jfrog.io/docker/hello-world:1.0.0"
        ports:
        - containerPort: 8080
