# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Values.name }}
# spec:
#   type: {{ .Values.serviceType }}
#   selector:
#     app: {{ .Values.app }}
#   ports:
#     - protocol: TCP
#       port: {{ .Values.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: LoadBalancer
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 8080